# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('med_information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='record',
            name='diastolic_pressure',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='systolic_pressure',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 22, 46, 55, 928421, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='heart_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='height',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='respirations_minute',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 22, 46, 55, 934567, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='comments',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='result',
            name='test_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 22, 46, 56, 44460, tzinfo=utc), null=True),
        ),
    ]
