# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
