# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 21:22
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User, Permission
from django.contrib.contenttypes.models import ContentType

def create_admin(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Person = apps.get_model('users', 'Person')
    Person.objects.using(db_alias).all().delete()

    Hospital = apps.get_model('users', 'Hospital')
    hospital = Hospital.objects.using(db_alias).get(pk=1)

    Admin = apps.get_model('users', 'Admin')
    user = User.objects.using(db_alias).get(pk=3)
    Admin.objects.using(db_alias).create(name="Jane Doe", is_admin=True,
                                         user_id=user.id,
                                         hospital=hospital)
    admin = Admin.objects.using(db_alias).get(name="Jane Doe")
    content_type = ContentType.objects.get_for_model(apps.get_model('users', 'Patient'))
    permission = Permission.objects.get(
        codename='update_patient',
        content_type=content_type,
    )
    admin.user.user_permissions.add(permission.id)

def delete_admin(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Admin = apps.get_model('users', 'Admin')
    Admin.objects.using(db_alias).get(name="Jane Doe").delete()
    User.objects.using(db_alias).get(pk=3).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin, delete_admin),
    ]
