# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 21:22
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.management import create_permissions

def migrate_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

def create_user(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model('auth','User')
    User.objects.using(db_alias).create(username="admin", password="pbkdf2_sha256$36000$sPr6g8qk2ghI$4WRKCYwkafGcJSnPWbfEq4ePEF8L9CkdTJEaF+s7dfM=")
    User.objects.using(db_alias).create(username="doctor", password="pbkdf2_sha256$36000$sPr6g8qk2ghI$4WRKCYwkafGcJSnPWbfEq4ePEF8L9CkdTJEaF+s7dfM=")
    User.objects.using(db_alias).create(username="nurse", password="pbkdf2_sha256$36000$sPr6g8qk2ghI$4WRKCYwkafGcJSnPWbfEq4ePEF8L9CkdTJEaF+s7dfM=")
    Hospital = apps.get_model('users','Hospital')
    Hospital.objects.using(db_alias).create(name="Strong Memorial Hospital", address="Somewhere in Rochester")
    Hospital.objects.using(db_alias).create(name="UoR Hospital", address="Somewhere in Rochester")

def delete_user(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Hospital = apps.get_model('users','Hospital')
    Hospital.objects.using(db_alias).get(name="UoR").delete()
    Hospital.objects.using(db_alias).get(name="Strong Memorial Hospital").delete()
    User = apps.get_model('auth','User')
    User.objects.using(db_alias).get(username="adminUnique").delete()

def create_admin(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Person = apps.get_model('users', 'Person')
    Person.objects.using(db_alias).all().delete()

    Hospital = apps.get_model('users', 'Hospital')
    hospital = Hospital.objects.using(db_alias).get(name="UoR Hospital")

    Admin = apps.get_model('users', 'Admin')
    user = User.objects.using(db_alias).get(username="admin")
    Admin.objects.using(db_alias).create(name="Jane Doe", is_admin=True,
                                         user_id=user.id,
                                         hospital=hospital)
    admin = Admin.objects.using(db_alias).get(name="Jane Doe")
    content_type = ContentType.objects.get_for_model(apps.get_model('users', 'Patient'))
    permission = Permission.objects.get(
        codename='update_patient',
        content_type=content_type,
    )
    admin.user.user_permissions.add(permission.id)
    content_type = ContentType.objects.get_for_model(apps.get_model('users', 'Admin'))
    permission = Permission.objects.get(
        codename='update',
        content_type=content_type,
    )
    admin.user.user_permissions.add(permission.id)
    permission = Permission.objects.get(
        codename='transfer',
        content_type=content_type,
    )
    admin.user.user_permissions.add(permission.id)

    Doctor = apps.get_model('users', 'Doctor')
    user = User.objects.using(db_alias).get(username="doctor")
    Doctor.objects.using(db_alias).create(name="John Smith", is_admin=True,
                                         user_id=user.id,
                                         hospital=hospital)
    doctor = Doctor.objects.using(db_alias).get(user_id=user.id)

    Nurse = apps.get_model('users', 'Doctor')
    user = User.objects.using(db_alias).get(username="nurse")
    Nurse.objects.using(db_alias).create(name="John Doe", is_admin=True,
                                          user_id=user.id,
                                          hospital=hospital)
    nurse = Nurse.objects.using(db_alias).get(user_id=user.id)
    content_type = ContentType.objects.get_for_model(apps.get_model('users', 'Doctor'))
    permission = Permission.objects.get(
        codename='admit',
        content_type=content_type,
    )
    doctor.user.user_permissions.add(permission.id)
    nurse.user.user_permissions.add(permission.id)
    content_type = ContentType.objects.get_for_model(apps.get_model('users', 'Doctor'))
    permission = Permission.objects.get(
        codename='release',
        content_type=content_type,
    )
    doctor.user.user_permissions.add(permission.id)
    nurse.user.user_permissions.add(permission.id)
    doctor.save()
    nurse.save()
    admin.save()

def delete_admin(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Admin = apps.get_model('users', 'Admin')
    Admin.objects.using(db_alias).get(name="Jane Doe").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_permissions),
        migrations.RunPython(create_user,  delete_user),
        migrations.RunPython(create_admin, delete_admin),
    ]
