# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170721_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
